// ============================================================================
// Hardcoded field options for category, type, categoryGear, and subtype
// These values are extracted from the database
// To update: Run dashboard/scripts/extract-field-values.js
// ============================================================================

export const FIELD_OPTIONS = {
  category: [
    "Armor",
    "Material",
    "Recipe",
    "Weapon"
  ],
  type: [
    "1h",
    "2h",
    "Ancient Parts",
    "Chest",
    "Creature",
    "Dairy",
    "Fish",
    "Fruit",
    "Fungi",
    "Grain",
    "Head",
    "Inedible",
    "Legs",
    "Meat",
    "Monster",
    "Mushroom",
    "Natural",
    "Ore",
    "Plant",
    "Potion",
    "Protein",
    "Seafood",
    "Special",
    "Sweets",
    "Vegetable"
  ],
  categoryGear: [
    "Armor",
    "None",
    "Weapon"
  ],
  subtype: [
    "Arm",
    "Armor",
    "Arrow",
    "Axe",
    "Bandanna",
    "Boomerang",
    "Boots",
    "Bow",
    "Cap",
    "Carver",
    "Circlet",
    "Club",
    "Crusher",
    "Cuirass",
    "Doublet",
    "Earrings",
    "Gear",
    "Greaves",
    "Guard",
    "Hammer",
    "Headband",
    "Headdress",
    "Headpiece",
    "Helm",
    "Hood",
    "Leaf",
    "Leg Wraps",
    "Legwear",
    "Mask",
    "None",
    "Polearm",
    "Robe",
    "Rod",
    "Shield",
    "Shirt",
    "Sickle",
    "Sirwal",
    "Spaulder",
    "Spear",
    "Sword",
    "Tights",
    "Top",
    "Trousers",
    "Tunic",
    "Uniform",
    "Veil"
  ],
  element: [
    "none",
    "fire",
    "ice",
    "electric",
    "tech"
  ],
};
