// ============================================================================
// ------------------- Model Configurations -------------------
// Central configuration for all database models in the admin editor
// ============================================================================

import type { ModelConfig } from "../types/model-types";
import { FIELD_OPTIONS } from "../constants/field-options";

export const MODEL_CONFIGS: Record<string, ModelConfig> = {
  Item: {
    name: "Item",
    displayName: "Items",
    icon: "fa-cube",
    collection: "items",
    nameField: "itemName",
    sortField: "itemName",
    filterKeys: ["category", "type", "rarity", "categoryGear", "subtype", "source", "location", "job", "craftable", "stackable"],
    tabs: [
      {
        id: "basics",
        label: "Basics",
        icon: "fa-tag",
        fields: [
          {
            key: "itemName",
            label: "Item Name",
            type: "text",
            helpText: "The name of the item",
            required: true,
          },
          {
            key: "image",
            label: "Image URL",
            type: "text",
            helpText: "URL to the item image",
          },
          {
            key: "imageType",
            label: "Image Type",
            type: "text",
            helpText: "Type of image (e.g., 'png', 'jpg')",
          },
          {
            key: "emoji",
            label: "Emoji",
            type: "text",
            helpText: "Discord emoji code for the item",
          },
          {
            key: "itemRarity",
            label: "Rarity",
            type: "number",
            helpText: "Item rarity level",
            min: 0,
            max: 10,
          },
          {
            key: "buyPrice",
            label: "Buy Price",
            type: "number",
            helpText: "Price to buy this item",
            min: 0,
          },
          {
            key: "sellPrice",
            label: "Sell Price",
            type: "number",
            helpText: "Price to sell this item",
            min: 0,
          },
          {
            key: "modifierHearts",
            label: "Hearts Restored",
            type: "number",
            helpText: "Hearts restored when consumed",
            min: 0,
            getLabel: (data) => {
              const categoryGear = Array.isArray(data.categoryGear) 
                ? data.categoryGear[0] 
                : data.categoryGear;
              return categoryGear === "Armor" || categoryGear === "Weapon" 
                ? "Modifier" 
                : "Hearts Restored";
            },
            getHelpText: (data) => {
              const categoryGear = Array.isArray(data.categoryGear) 
                ? data.categoryGear[0] 
                : data.categoryGear;
              return categoryGear === "Armor" || categoryGear === "Weapon"
                ? "Modifier value for armor/weapon"
                : "Hearts restored when consumed";
            },
          },
          {
            key: "staminaRecovered",
            label: "Stamina Recovered",
            type: "number",
            helpText: "Stamina recovered when consumed",
            min: 0,
          },
          {
            key: "stackable",
            label: "Stackable",
            type: "boolean",
            helpText: "Whether this item can be stacked",
          },
          {
            key: "maxStackSize",
            label: "Max Stack Size",
            type: "number",
            helpText: "Maximum stack size for this item",
            min: 1,
            showIf: (data) => data.stackable === true,
          },
        ],
      },
      {
        id: "classification",
        label: "Classification",
        icon: "fa-layer-group",
        fields: [
          {
            key: "category",
            label: "Category",
            type: "multiselect",
            helpText: "Item categories",
            options: FIELD_OPTIONS.category.map(cat => ({ value: cat, label: cat })),
          },
          {
            key: "type",
            label: "Type",
            type: "multiselect",
            helpText: "Item types",
            options: FIELD_OPTIONS.type.map(t => ({ value: t, label: t })),
          },
          {
            key: "categoryGear",
            label: "Gear Type",
            type: "select",
            helpText: "Category for gear items",
            options: FIELD_OPTIONS.categoryGear.map(cg => ({ value: cg, label: cg })),
          },
          {
            key: "subtype",
            label: "Subtype",
            type: "multiselect",
            helpText: "Item subtypes",
            options: FIELD_OPTIONS.subtype.map(st => ({ value: st, label: st })),
          },
          {
            key: "element",
            label: "Element",
            type: "select",
            helpText: "Elemental type for weapons/armor (fire, ice, electric, tech, none)",
            options: FIELD_OPTIONS.element.map(el => ({ value: el, label: el.charAt(0).toUpperCase() + el.slice(1) })),
            showIf: (data) => {
              const categoryGear = Array.isArray(data.categoryGear) 
                ? data.categoryGear[0] 
                : data.categoryGear;
              return categoryGear === "Armor" || categoryGear === "Weapon";
            },
          },
        ],
      },
      {
        id: "crafting",
        label: "Crafting",
        icon: "fa-hammer",
        fields: [
          {
            key: "crafting",
            label: "Craftable",
            type: "boolean",
            helpText: "Whether this item can be crafted",
          },
          {
            key: "staminaToCraft",
            label: "Stamina to Craft",
            type: "number",
            helpText: "Stamina required to craft this item",
            min: 0,
            showIf: (data) => data.crafting === true,
          },
          {
            key: "craftingMaterial",
            label: "Crafting Materials",
            type: "custom",
            component: "CraftingMaterialsField",
            helpText: "Materials needed to craft this item",
            showIf: (data) => data.crafting === true,
          },
        ],
      },
      {
        id: "activities",
        label: "Activities",
        icon: "fa-compass",
        fields: [
          {
            key: "activities",
            label: "Activities",
            type: "toggle-grid",
            helpText: "Please select and highlight the buttons below to enable them - ways to obtain this item",
            columns: 3,
            options: [
              { value: "gathering", label: "Gathering" },
              { value: "looting", label: "Looting" },
              { value: "crafting", label: "Crafting" },
              { value: "traveling", label: "Traveling" },
              { value: "exploring", label: "Exploring" },
              { value: "vending", label: "Vending" },
            ],
          },
        ],
      },
      {
        id: "weather",
        label: "Weather",
        icon: "fa-cloud-sun",
        fields: [
          {
            key: "weather",
            label: "Weather Conditions",
            type: "toggle-grid",
            helpText: "Please select and highlight the buttons below to enable them - special weather conditions",
            columns: 2,
            options: [
              { value: "muggy", label: "Muggy" },
              { value: "flowerbloom", label: "Flowerbloom" },
              { value: "fairycircle", label: "Fairy Circle" },
              { value: "jubilee", label: "Jubilee" },
              { value: "meteorShower", label: "Meteor Shower" },
              { value: "rockslide", label: "Rockslide" },
              { value: "avalanche", label: "Avalanche" },
            ],
          },
        ],
      },
      {
        id: "pet",
        label: "Pet Perks",
        icon: "fa-paw",
        fields: [
          {
            key: "petTypes",
            label: "Pet Types",
            type: "toggle-grid",
            helpText: "Please select and highlight the buttons below to enable them - pet types that can obtain this item",
            columns: 2,
            groupTitle: "Pet Types",
            options: [
              { value: "petprey", label: "Prey" },
              { value: "petforage", label: "Forage" },
              { value: "lgpetprey", label: "Large Prey" },
              { value: "petmon", label: "Monster" },
            ],
          },
          {
            key: "chuchuVariants",
            label: "Chuchu Variants",
            type: "toggle-grid",
            helpText: "Please select and highlight the buttons below to enable them - Chuchu variants",
            columns: 2,
            groupTitle: "Chuchu Variants",
            options: [
              { value: "petchu", label: "Chuchu" },
              { value: "petfirechu", label: "Fire Chuchu" },
              { value: "peticechu", label: "Ice Chuchu" },
              { value: "petelectricchu", label: "Electric Chuchu" },
            ],
          },
        ],
      },
      {
        id: "locations",
        label: "Locations",
        icon: "fa-map",
        fields: [
          {
            key: "regions",
            label: "Regions",
            type: "toggle-grid",
            helpText: "Please select and highlight the buttons below to enable them - regions where this item can be found",
            columns: 2,
            groupTitle: "Regions",
            options: [
              { value: "centralHyrule", label: "Central Hyrule" },
              { value: "eldin", label: "Eldin" },
              { value: "faron", label: "Faron" },
              { value: "gerudo", label: "Gerudo" },
              { value: "hebra", label: "Hebra" },
              { value: "lanayru", label: "Lanayru" },
            ],
          },
          {
            key: "specialPaths",
            label: "Special Paths",
            type: "toggle-grid",
            helpText: "Please select and highlight the buttons below to enable them - special paths",
            columns: 2,
            groupTitle: "Special Paths",
            options: [
              { value: "pathOfScarletLeaves", label: "Path of Scarlet Leaves" },
              { value: "leafDewWay", label: "Leaf Dew Way" },
            ],
          },
        ],
      },
      {
        id: "jobs",
        label: "Jobs",
        icon: "fa-briefcase",
        fields: [
          {
            key: "gatheringJobs",
            label: "Gathering Jobs",
            type: "toggle-grid",
            helpText: "Please select and highlight the buttons below to enable them - gathering jobs",
            columns: 3,
            groupTitle: "Gathering Jobs",
            options: [
              { value: "farmer", label: "Farmer" },
              { value: "forager", label: "Forager" },
              { value: "rancher", label: "Rancher" },
              { value: "herbalist", label: "Herbalist" },
              { value: "fisherman", label: "Fisherman" },
              { value: "miner", label: "Miner" },
            ],
          },
          {
            key: "craftingJobs",
            label: "Crafting Jobs",
            type: "toggle-grid",
            helpText: "Please select and highlight the buttons below to enable them - crafting jobs",
            columns: 3,
            groupTitle: "Crafting Jobs",
            options: [
              { value: "blacksmith", label: "Blacksmith" },
              { value: "cook", label: "Cook" },
              { value: "craftsman", label: "Craftsman" },
              { value: "beekeeper", label: "Beekeeper" },
              { value: "weaver", label: "Weaver" },
              { value: "maskMaker", label: "Mask Maker" },
            ],
          },
          {
            key: "lootingJobs",
            label: "Looting Jobs",
            type: "toggle-grid",
            helpText: "Please select and highlight the buttons below to enable them - looting jobs",
            columns: 3,
            groupTitle: "Looting Jobs",
            options: [
              { value: "adventurer", label: "Adventurer" },
              { value: "guard", label: "Guard" },
              { value: "gravekeeper", label: "Gravekeeper" },
              { value: "hunter", label: "Hunter" },
              { value: "hunterLooting", label: "Hunter (Looting)" },
              { value: "mercenary", label: "Mercenary" },
              { value: "scout", label: "Scout" },
              { value: "artist", label: "Artist" },
              { value: "researcher", label: "Researcher" },
              { value: "witch", label: "Witch" },
            ],
          },
        ],
      },
      {
        id: "monsters",
        label: "Monsters",
        icon: "fa-dragon",
        fields: [
          {
            key: "monsters",
            label: "Monster Variants",
            type: "toggle-grid",
            helpText: "Please select and highlight the buttons below to enable them - monster variants that drop this item",
            columns: 3,
            options: [
              // This would be populated dynamically or from a large list
              { value: "bokoblin", label: "Bokoblin" },
              { value: "moblin", label: "Moblin" },
              { value: "lizalfos", label: "Lizalfos" },
              // ... more monsters
            ],
          },
        ],
      },
    ],
  },
  Monster: {
    name: "Monster",
    displayName: "Monsters",
    icon: "fa-dragon",
    collection: "monsters",
    nameField: "name",
    sortField: "name",
    filterKeys: ["species", "type", "tier"],
    tabs: [
      {
        id: "basics",
        label: "Basics",
        icon: "fa-tag",
        fields: [
          {
            key: "name",
            label: "Name",
            type: "text",
            helpText: "The name of the monster",
            required: true,
          },
          {
            key: "nameMapping",
            label: "Name Mapping",
            type: "text",
            helpText: "Key format for mapping",
            required: true,
          },
          {
            key: "image",
            label: "Image URL",
            type: "text",
            helpText: "URL to the monster image",
          },
          {
            key: "species",
            label: "Species",
            type: "text",
            helpText: "Monster species",
          },
          {
            key: "type",
            label: "Type",
            type: "text",
            helpText: "Monster type",
          },
          {
            key: "tier",
            label: "Tier",
            type: "number",
            helpText: "Monster tier level",
            min: 1,
            max: 10,
          },
          {
            key: "hearts",
            label: "Hearts",
            type: "number",
            helpText: "Monster health/hearts",
            min: 0,
          },
          {
            key: "dmg",
            label: "Damage",
            type: "number",
            helpText: "Monster damage",
            min: 0,
          },
          {
            key: "bloodmoon",
            label: "Bloodmoon",
            type: "boolean",
            helpText: "Select to make it true - whether this monster appears during bloodmoon",
          },
        ],
        gridColumns: 2, // Add grid layout support
      },
      {
        id: "locations",
        label: "Locations",
        icon: "fa-map",
        fields: [
          {
            key: "regions",
            label: "Regions",
            type: "toggle-grid",
            helpText: "Please select and highlight the buttons below to enable them - regions where this monster can be found",
            columns: 2,
            groupTitle: "Regions",
            options: [
              { value: "centralHyrule", label: "Central Hyrule" },
              { value: "eldin", label: "Eldin" },
              { value: "faron", label: "Faron" },
              { value: "gerudo", label: "Gerudo" },
              { value: "hebra", label: "Hebra" },
              { value: "lanayru", label: "Lanayru" },
            ],
          },
          {
            key: "specialPaths",
            label: "Special Paths",
            type: "toggle-grid",
            helpText: "Please select and highlight the buttons below to enable them - special paths",
            columns: 2,
            groupTitle: "Special Paths",
            options: [
              { value: "pathOfScarletLeaves", label: "Path of Scarlet Leaves" },
              { value: "leafDewWay", label: "Leaf Dew Way" },
            ],
          },
          {
            key: "exploreRegions",
            label: "Explore Regions",
            type: "toggle-grid",
            helpText: "Please select and highlight the buttons below to enable them - explore regions (will auto-populate Explore Locations)",
            columns: 2,
            groupTitle: "Explore Regions",
            options: [
              { value: "exploreEldin", label: "Eldin" },
              { value: "exploreLanayru", label: "Lanayru" },
              { value: "exploreFaron", label: "Faron" },
            ],
          },
          {
            key: "exploreLocations",
            label: "Explore Locations",
            type: "array",
            helpText: "Auto-populated based on selected Explore Regions. Additional explore locations can be added manually.",
            readOnly: false,
            autoPopulated: true, // Shows auto-populated badge but still allows editing
          },
        ],
      },
      {
        id: "jobs",
        label: "Jobs",
        icon: "fa-briefcase",
        fields: [
          {
            key: "monsterJobs",
            label: "Monster Jobs",
            type: "toggle-grid",
            helpText: "Please select and highlight the buttons below to enable them - jobs associated with this monster",
            columns: 3,
            options: [
              { value: "adventurer", label: "Adventurer" },
              { value: "guard", label: "Guard" },
              { value: "graveskeeper", label: "Gravekeeper" },
              { value: "hunter", label: "Hunter" },
              { value: "mercenary", label: "Mercenary" },
              { value: "scout", label: "Scout" },
              { value: "rancher", label: "Rancher" },
              { value: "beekeeper", label: "Beekeeper" },
              { value: "farmer", label: "Farmer" },
              { value: "fisherman", label: "Fisherman" },
              { value: "forager", label: "Forager" },
              { value: "herbalist", label: "Herbalist" },
              { value: "miner", label: "Miner" },
            ],
          },
        ],
      },
    ],
  },
  Pet: {
    name: "Pet",
    displayName: "Pets",
    icon: "fa-paw",
    collection: "pets",
    nameField: "name",
    sortField: "name",
    filterKeys: ["status", "species", "petType"],
    tabs: [
      {
        id: "basics",
        label: "Basics",
        icon: "fa-tag",
        fields: [
          {
            key: "name",
            label: "Name",
            type: "text",
            helpText: "The name of the pet",
            required: true,
          },
          {
            key: "species",
            label: "Species",
            type: "select",
            helpText: "Pet species (must match bot options)",
            required: true,
            options: [
              { value: "amphibian", label: "Amphibian" },
              { value: "bovine", label: "Bovine" },
              { value: "caprine", label: "Caprine" },
              { value: "climbingReptile", label: "Climbing Reptile" },
              { value: "flightlessBird", label: "Flightless Bird" },
              { value: "foragingBird", label: "Foraging Bird" },
              { value: "largeCanine", label: "Large Canine" },
              { value: "largeFeline", label: "Large Feline" },
              { value: "lagamorph", label: "Lagamorph" },
              { value: "marsupial", label: "Marsupial" },
              { value: "mesopredator", label: "Mesopredator" },
              { value: "mustelid", label: "Mustelid" },
              { value: "ovine", label: "Ovine" },
              { value: "porcine", label: "Porcine" },
              { value: "predatoryBird", label: "Predatory Bird" },
              { value: "rodent", label: "Rodent" },
              { value: "scavengingBird", label: "Scavenging Bird" },
              { value: "shellReptile", label: "Shell Reptile" },
              { value: "smallCanine", label: "Small Canine" },
              { value: "smallFeline", label: "Small Feline" },
              { value: "smallReptile", label: "Small Reptile" },
              { value: "Choir Frog", label: "Choir Frog" },
              { value: "chainChomp", label: "Chain Chomp" },
              { value: "chuchu", label: "Chuchu" },
              { value: "cucco", label: "Cucco" },
              { value: "keese", label: "Keese" },
              { value: "moink", label: "Moink" },
              { value: "pol's voice", label: "Pol's Voice" },
              { value: "pygmyOctorok", label: "Pygmy Octorok" },
              { value: "remlit", label: "Remlit" },
              { value: "sand seal", label: "Sand Seal" },
              { value: "walltula", label: "Walltula" },
              { value: "smallspecial", label: "Small Special" },
              { value: "largespecial", label: "Large Special" },
            ],
          },
          {
            key: "petType",
            label: "Pet Type",
            type: "select",
            helpText: "Type of pet (must match bot options)",
            required: true,
            options: [
              { value: "Chuchu", label: "Chuchu" },
              { value: "FireChuchu", label: "Fire Chuchu" },
              { value: "IceChuchu", label: "Ice Chuchu" },
              { value: "ElectricChuchu", label: "Electric Chuchu" },
              { value: "Conqueror", label: "Conqueror" },
              { value: "Explorer", label: "Explorer" },
              { value: "Forager", label: "Forager" },
              { value: "Guardian", label: "Guardian" },
              { value: "Hunter", label: "Hunter" },
              { value: "Nomad", label: "Nomad" },
              { value: "Omnivore", label: "Omnivore" },
              { value: "Protector", label: "Protector" },
              { value: "Prowler", label: "Prowler" },
              { value: "Ranger", label: "Ranger" },
              { value: "Roamer", label: "Roamer" },
              { value: "Scavenger", label: "Scavenger" },
              { value: "Sentinel", label: "Sentinel" },
              { value: "Tracker", label: "Tracker" },
            ],
          },
          {
            key: "level",
            label: "Level",
            type: "number",
            helpText: "Pet level",
            min: 0,
          },
          {
            key: "imageUrl",
            label: "Image URL",
            type: "text",
            helpText: "URL to the pet image",
          },
        ],
      },
      {
        id: "owner",
        label: "Owner",
        icon: "fa-user",
        fields: [
          {
            key: "ownerName",
            label: "Owner Name",
            type: "text",
            helpText: "Name of the pet owner",
            required: true,
          },
          {
            key: "discordId",
            label: "Discord ID",
            type: "text",
            helpText: "Discord ID of the owner",
            required: true,
          },
          {
            key: "owner",
            label: "Owner ID",
            type: "text",
            helpText: "Character ID of the owner",
            required: true,
          },
        ],
      },
      {
        id: "status",
        label: "Status",
        icon: "fa-info-circle",
        fields: [
          {
            key: "status",
            label: "Status",
            type: "select",
            helpText: "Pet status",
            options: [
              { value: "active", label: "Active" },
              { value: "stored", label: "Stored" },
              { value: "retired", label: "Retired" },
              { value: "for_sale", label: "For Sale" },
            ],
          },
          {
            key: "storageLocation",
            label: "Storage Location",
            type: "text",
            helpText: "Where the pet is stored",
            showIf: (data) => data.status === "stored",
          },
          {
            key: "storedAt",
            label: "Stored At",
            type: "date",
            helpText: "When the pet was stored",
            showIf: (data) => data.status === "stored",
          },
          {
            key: "removedFromStorageAt",
            label: "Removed From Storage At",
            type: "date",
            helpText: "When the pet was removed from storage",
          },
        ],
      },
      {
        id: "attributes",
        label: "Attributes",
        icon: "fa-star",
        fields: [
          {
            key: "rollsRemaining",
            label: "Rolls Remaining",
            type: "number",
            helpText: "Number of rolls remaining",
            min: 0,
          },
          {
            key: "rollCombination",
            label: "Roll Combination",
            type: "array",
            helpText: "Auto-filled from Pet Type; edit if needed",
          },
          {
            key: "tableDescription",
            label: "Table Description",
            type: "text",
            helpText: "Auto-filled from Pet Type; edit if needed",
          },
          {
            key: "lastRollDate",
            label: "Last Roll Date",
            type: "date",
            helpText: "Date of last roll",
          },
        ],
      },
    ],
  },
  Character: {
    name: "Character",
    displayName: "Characters",
    icon: "fa-user",
    collection: "characters",
    nameField: "name",
    sortField: "name",
    filterKeys: ["race", "village", "job"],
    tabs: [
      {
        id: "basics",
        label: "Basics",
        icon: "fa-tag",
        gridColumns: 2,
        fields: [
          {
            key: "name",
            label: "Name",
            type: "text",
            helpText: "Character name",
            required: true,
          },
          {
            key: "userId",
            label: "User ID",
            type: "text",
            helpText: "Discord user ID",
            required: true,
          },
          {
            key: "icon",
            label: "Icon",
            type: "text",
            helpText: "Character icon URL",
            required: true,
          },
          {
            key: "status",
            label: "Status",
            type: "select",
            helpText: "Character status",
            options: [
              { value: "pending", label: "Pending" },
              { value: "accepted", label: "Accepted" },
              { value: "needs_changes", label: "Needs Changes" },
            ],
          },
          {
            key: "pronouns",
            label: "Pronouns",
            type: "text",
            helpText: "Character pronouns",
            required: true,
          },
          {
            key: "gender",
            label: "Gender",
            type: "text",
            helpText: "Gender and pronouns (e.g., 'Female | she/her')",
          },
          {
            key: "race",
            label: "Race",
            type: "text",
            helpText: "Character race",
            required: true,
          },
          {
            key: "virtue",
            label: "Virtue",
            type: "select",
            helpText: "Character virtue",
            options: [
              { value: "power", label: "Power" },
              { value: "wisdom", label: "Wisdom" },
              { value: "courage", label: "Courage" },
              { value: "TBA", label: "TBA" },
              { value: "tba", label: "tba" },
            ],
          },
          {
            key: "age",
            label: "Age",
            type: "number",
            helpText: "Character age",
            min: 0,
          },
          {
            key: "height",
            label: "Height",
            type: "number",
            helpText: "Character height",
            min: 0,
          },
          {
            key: "birthday",
            label: "Birthday",
            type: "text",
            helpText: "Character birthday",
          },
          {
            key: "homeVillage",
            label: "Home Village",
            type: "text",
            helpText: "Character's home village",
            required: true,
          },
          {
            key: "currentVillage",
            label: "Current Village",
            type: "text",
            helpText: "Character's current village",
          },
          {
            key: "job",
            label: "Job",
            type: "text",
            helpText: "Character's job",
            required: true,
          },
          {
            key: "jobDateChanged",
            label: "Job Date Changed",
            type: "date",
            helpText: "Date when job was changed",
          },
          {
            key: "inventory",
            label: "Inventory Link",
            type: "text",
            helpText: "Inventory URL (auto-generated)",
          },
          {
            key: "appLink",
            label: "App Link",
            type: "text",
            helpText: "External app link (obsolete)",
          },
          {
            key: "appArt",
            label: "App Art",
            type: "text",
            helpText: "URL to application art image",
          },
        ],
      },
      {
        id: "biography",
        label: "Biography",
        icon: "fa-book",
        gridColumns: 1,
        fields: [
          {
            key: "personality",
            label: "Personality",
            type: "text",
            helpText: "Character personality (suggestion: at least 5 sentences)",
            placeholder: "Describe the character's personality...",
          },
          {
            key: "history",
            label: "History",
            type: "text",
            helpText: "Character history (suggestion: at least 5 sentences)",
            placeholder: "Describe the character's history...",
          },
          {
            key: "extras",
            label: "Extras",
            type: "text",
            helpText: "Additional information (optional)",
            placeholder: "Any additional information...",
          },
        ],
      },
      {
        id: "health",
        label: "Health & Stamina",
        icon: "fa-heart",
        gridColumns: 2,
        fields: [
          {
            key: "maxHearts",
            label: "Max Hearts",
            type: "number",
            helpText: "Maximum hearts",
            required: true,
            min: 0,
          },
          {
            key: "currentHearts",
            label: "Current Hearts",
            type: "number",
            helpText: "Current hearts",
            required: true,
            min: 0,
          },
          {
            key: "maxStamina",
            label: "Max Stamina",
            type: "number",
            helpText: "Maximum stamina",
            required: true,
            min: 0,
          },
          {
            key: "currentStamina",
            label: "Current Stamina",
            type: "number",
            helpText: "Current stamina",
            required: true,
            min: 0,
          },
          {
            key: "lastStaminaUsage",
            label: "Last Stamina Usage",
            type: "date",
            helpText: "Date of last stamina usage",
          },
          {
            key: "lastSpecialWeatherGather",
            label: "Last Special Weather Gather",
            type: "date",
            helpText: "Date of last special weather gathering",
          },
        ],
      },
      {
        id: "gear",
        label: "Gear & Stats",
        icon: "fa-shield",
        gridColumns: 2,
        fields: [
          {
            key: "gearArmor.head.name",
            label: "Head Armor",
            type: "text",
            helpText: "Head armor name",
          },
          {
            key: "gearArmor.chest.name",
            label: "Chest Armor",
            type: "text",
            helpText: "Chest armor name",
          },
          {
            key: "gearArmor.legs.name",
            label: "Legs Armor",
            type: "text",
            helpText: "Legs armor name",
          },
          {
            key: "gearWeapon.name",
            label: "Weapon",
            type: "text",
            helpText: "Weapon name",
          },
          {
            key: "gearShield.name",
            label: "Shield",
            type: "text",
            helpText: "Shield name",
          },
          {
            key: "attack",
            label: "Attack",
            type: "number",
            helpText: "Attack stat",
            min: 0,
          },
          {
            key: "defense",
            label: "Defense",
            type: "number",
            helpText: "Defense stat",
            min: 0,
          },
        ],
      },
      {
        id: "vendor",
        label: "Vendor & Shop",
        icon: "fa-store",
        gridColumns: 2,
        fields: [
          {
            key: "vendingPoints",
            label: "Vending Points",
            type: "number",
            helpText: "Vending points",
            min: 0,
          },
          {
            key: "vendorType",
            label: "Vendor Type",
            type: "text",
            helpText: "Type of vendor",
          },
          {
            key: "shopPouch",
            label: "Shop Pouch",
            type: "text",
            helpText: "Shop pouch identifier",
          },
          {
            key: "pouchSize",
            label: "Pouch Size",
            type: "number",
            helpText: "Pouch size",
            min: 0,
          },
          {
            key: "shopLink",
            label: "Shop Link",
            type: "text",
            helpText: "Shop link URL",
          },
          {
            key: "shopImage",
            label: "Shop Image",
            type: "text",
            helpText: "Shop image URL",
          },
          {
            key: "lastCollectedMonth",
            label: "Last Collected Month",
            type: "number",
            helpText: "Last month tokens were collected",
            min: 0,
            max: 12,
          },
          {
            key: "vendingSync",
            label: "Vending Sync",
            type: "boolean",
            helpText: "Select to make it true - whether vending is synced",
          },
          {
            key: "vendingSetup.shopLink",
            label: "Vending Setup – Shop Link",
            type: "text",
            helpText: "Shop link from vending setup",
          },
          {
            key: "vendingSetup.pouchType",
            label: "Vending Setup – Pouch Type",
            type: "text",
            helpText: "Pouch type from vending setup",
          },
          {
            key: "vendingSetup.shopImage",
            label: "Vending Setup – Shop Image",
            type: "text",
            helpText: "Shop image URL from vending setup",
          },
          {
            key: "vendingSetup.setupDate",
            label: "Vending Setup – Setup Date",
            type: "date",
            helpText: "When vending was set up",
          },
        ],
      },
      {
        id: "status",
        label: "Status & Effects",
        icon: "fa-info-circle",
        gridColumns: 2,
        fields: [
          {
            key: "blighted",
            label: "Blighted",
            type: "boolean",
            helpText: "Select to make it true - whether the character is blighted",
          },
          {
            key: "blightedAt",
            label: "Blighted At",
            type: "date",
            helpText: "Date when character became blighted",
            showIf: (data) => data.blighted === true,
          },
          {
            key: "blightStage",
            label: "Blight Stage",
            type: "number",
            helpText: "Blight stage level",
            min: 0,
            showIf: (data) => data.blighted === true,
          },
          {
            key: "blightPaused",
            label: "Blight Paused",
            type: "boolean",
            helpText: "Select to make it true - whether blight progression is paused",
            showIf: (data) => data.blighted === true,
          },
          {
            key: "lastRollDate",
            label: "Last Roll Date",
            type: "date",
            helpText: "Date of last blight roll",
            showIf: (data) => data.blighted === true,
          },
          {
            key: "deathDeadline",
            label: "Death Deadline",
            type: "date",
            helpText: "Deadline for character death",
            showIf: (data) => data.blighted === true,
          },
          {
            key: "blightPauseInfo.pausedAt",
            label: "Blight Pause – Paused At",
            type: "date",
            helpText: "When blight was paused",
            showIf: (data) => data.blighted === true && data.blightPaused === true,
          },
          {
            key: "blightPauseInfo.pausedBy",
            label: "Blight Pause – Paused By (ID)",
            type: "text",
            helpText: "User ID who paused blight",
            showIf: (data) => data.blighted === true && data.blightPaused === true,
          },
          {
            key: "blightPauseInfo.pausedByUsername",
            label: "Blight Pause – Paused By (Username)",
            type: "text",
            helpText: "Username who paused blight",
            showIf: (data) => data.blighted === true && data.blightPaused === true,
          },
          {
            key: "blightPauseInfo.reason",
            label: "Blight Pause – Reason",
            type: "text",
            helpText: "Reason for pausing blight",
            showIf: (data) => data.blighted === true && data.blightPaused === true,
          },
          {
            key: "blightEffects.rollMultiplier",
            label: "Blight Effects – Roll Multiplier",
            type: "number",
            helpText: "Blight roll multiplier (e.g. 1.0)",
            showIf: (data) => data.blighted === true,
          },
          {
            key: "blightEffects.noMonsters",
            label: "Blight Effects – No Monsters",
            type: "boolean",
            helpText: "Blight effect: no monsters",
            showIf: (data) => data.blighted === true,
          },
          {
            key: "blightEffects.noGathering",
            label: "Blight Effects – No Gathering",
            type: "boolean",
            helpText: "Blight effect: no gathering",
            showIf: (data) => data.blighted === true,
          },
          {
            key: "ko",
            label: "KO",
            type: "boolean",
            helpText: "Select to make it true - whether character is knocked out",
          },
          {
            key: "debuff.active",
            label: "Debuff Active",
            type: "boolean",
            helpText: "Select to make it true - whether debuff is active",
          },
          {
            key: "debuff.endDate",
            label: "Debuff End Date",
            type: "date",
            helpText: "When debuff ends",
            showIf: (data) => (data.debuff as { active?: boolean })?.active === true,
          },
          {
            key: "buff.active",
            label: "Buff Active",
            type: "boolean",
            helpText: "Select to make it true - whether buff is active",
          },
          {
            key: "buff.type",
            label: "Buff Type",
            type: "select",
            helpText: "Type of buff elixir",
            options: [
              { value: "chilly", label: "Chilly" },
              { value: "electro", label: "Electro" },
              { value: "enduring", label: "Enduring" },
              { value: "energizing", label: "Energizing" },
              { value: "fireproof", label: "Fireproof" },
              { value: "hasty", label: "Hasty" },
              { value: "hearty", label: "Hearty" },
              { value: "mighty", label: "Mighty" },
              { value: "sneaky", label: "Sneaky" },
              { value: "spicy", label: "Spicy" },
              { value: "tough", label: "Tough" },
            ],
            showIf: (data) => {
              const buff = data.buff as { active?: boolean } | undefined;
              return buff?.active === true;
            },
          },
          {
            key: "buff.effects.blightResistance",
            label: "Buff – Blight Resistance",
            type: "number",
            helpText: "Chilly elixir",
            min: 0,
            showIf: (data) => (data.buff as { active?: boolean } | undefined)?.active === true,
          },
          {
            key: "buff.effects.electricResistance",
            label: "Buff – Electric Resistance",
            type: "number",
            helpText: "Electro elixir",
            min: 0,
            showIf: (data) => (data.buff as { active?: boolean } | undefined)?.active === true,
          },
          {
            key: "buff.effects.staminaBoost",
            label: "Buff – Stamina Boost",
            type: "number",
            helpText: "Enduring elixir",
            min: 0,
            showIf: (data) => (data.buff as { active?: boolean } | undefined)?.active === true,
          },
          {
            key: "buff.effects.staminaRecovery",
            label: "Buff – Stamina Recovery",
            type: "number",
            helpText: "Energizing elixir",
            min: 0,
            showIf: (data) => (data.buff as { active?: boolean } | undefined)?.active === true,
          },
          {
            key: "buff.effects.fireResistance",
            label: "Buff – Fire Resistance",
            type: "number",
            helpText: "Fireproof elixir",
            min: 0,
            showIf: (data) => (data.buff as { active?: boolean } | undefined)?.active === true,
          },
          {
            key: "buff.effects.speedBoost",
            label: "Buff – Speed Boost",
            type: "number",
            helpText: "Hasty elixir",
            min: 0,
            showIf: (data) => (data.buff as { active?: boolean } | undefined)?.active === true,
          },
          {
            key: "buff.effects.extraHearts",
            label: "Buff – Extra Hearts",
            type: "number",
            helpText: "Hearty elixir",
            min: 0,
            showIf: (data) => (data.buff as { active?: boolean } | undefined)?.active === true,
          },
          {
            key: "buff.effects.attackBoost",
            label: "Buff – Attack Boost",
            type: "number",
            helpText: "Mighty elixir",
            min: 0,
            showIf: (data) => (data.buff as { active?: boolean } | undefined)?.active === true,
          },
          {
            key: "buff.effects.stealthBoost",
            label: "Buff – Stealth Boost",
            type: "number",
            helpText: "Sneaky elixir",
            min: 0,
            showIf: (data) => (data.buff as { active?: boolean } | undefined)?.active === true,
          },
          {
            key: "buff.effects.coldResistance",
            label: "Buff – Cold Resistance",
            type: "number",
            helpText: "Spicy elixir",
            min: 0,
            showIf: (data) => (data.buff as { active?: boolean } | undefined)?.active === true,
          },
          {
            key: "buff.effects.defenseBoost",
            label: "Buff – Defense Boost",
            type: "number",
            helpText: "Tough elixir",
            min: 0,
            showIf: (data) => (data.buff as { active?: boolean } | undefined)?.active === true,
          },
          {
            key: "inJail",
            label: "In Jail",
            type: "boolean",
            helpText: "Select to make it true - whether character is in jail",
          },
          {
            key: "jailStartTime",
            label: "Jail Start Time",
            type: "date",
            helpText: "When character entered jail",
            showIf: (data) => data.inJail === true,
          },
          {
            key: "jailReleaseTime",
            label: "Jail Release Time",
            type: "date",
            helpText: "When character will be released",
            showIf: (data) => data.inJail === true,
          },
          {
            key: "jailDurationMs",
            label: "Jail Duration (ms)",
            type: "number",
            helpText: "Jail duration in milliseconds",
            showIf: (data) => data.inJail === true,
          },
          {
            key: "jailBoostSource",
            label: "Jail Boost Source",
            type: "text",
            helpText: "Source of jail boost",
            showIf: (data) => data.inJail === true,
          },
          {
            key: "canBeStolenFrom",
            label: "Can Be Stolen From",
            type: "boolean",
            helpText: "Select to make it true - whether character can be stolen from",
          },
          {
            key: "stealProtection.isProtected",
            label: "Steal Protection Active",
            type: "boolean",
            helpText: "Select to make it true - whether steal protection is active",
          },
          {
            key: "stealProtection.protectionEndTime",
            label: "Protection End Time",
            type: "date",
            helpText: "When protection ends",
            showIf: (data) => {
              const protection = data.stealProtection as { isProtected?: boolean } | undefined;
              return protection?.isProtected === true;
            },
          },
          {
            key: "failedStealAttempts",
            label: "Failed Steal Attempts",
            type: "number",
            helpText: "Number of failed steal attempts",
            min: 0,
          },
          {
            key: "failedFleeAttempts",
            label: "Failed Flee Attempts",
            type: "number",
            helpText: "Number of failed flee attempts",
            min: 0,
          },
        ],
      },
      {
        id: "companions",
        label: "Companions",
        icon: "fa-paw",
        gridColumns: 2,
        fields: [
          {
            key: "currentActivePet",
            label: "Current Active Pet",
            type: "text",
            helpText: "ID of currently active pet",
          },
          {
            key: "currentActiveMount",
            label: "Current Active Mount",
            type: "text",
            helpText: "ID of currently active mount",
          },
        ],
      },
      {
        id: "other",
        label: "Other",
        icon: "fa-cog",
        gridColumns: 2,
        fields: [
          {
            key: "spiritOrbs",
            label: "Spirit Orbs",
            type: "number",
            helpText: "Number of spirit orbs",
            min: 0,
          },
          {
            key: "jobVoucher",
            label: "Job Voucher",
            type: "boolean",
            helpText: "Select to make it true - whether character has job voucher (auto-reset to false)",
          },
          {
            key: "jobVoucherJob",
            label: "Job Voucher Job",
            type: "text",
            helpText: "Job from voucher (e.g. Fortune Teller). Shown when job voucher is used.",
          },
          {
            key: "boostedBy",
            label: "Boosted By",
            type: "text",
            helpText: "Character ID that is boosting this character",
          },
          {
            key: "helpWanted.lastCompletion",
            label: "Help Wanted – Last Completion",
            type: "text",
            helpText: "Last completion date (YYYY-MM-DD)",
          },
          {
            key: "helpWanted.cooldownUntil",
            label: "Help Wanted – Cooldown Until",
            type: "date",
            helpText: "Help Wanted cooldown end date",
          },
        ],
      },
      {
        id: "application",
        label: "Application",
        icon: "fa-file-lines",
        gridColumns: 2,
        fields: [
          {
            key: "applicationVersion",
            label: "Application Version",
            type: "number",
            helpText: "Application version number",
            min: 0,
          },
          {
            key: "submittedAt",
            label: "Submitted At",
            type: "date",
            helpText: "When character was submitted for review",
          },
          {
            key: "decidedAt",
            label: "Decided At",
            type: "date",
            helpText: "When mod decided on application",
          },
          {
            key: "approvedAt",
            label: "Approved At",
            type: "date",
            helpText: "When character was approved",
          },
          {
            key: "discordMessageId",
            label: "Discord Message ID",
            type: "text",
            helpText: "Discord message ID for application thread",
          },
          {
            key: "discordThreadId",
            label: "Discord Thread ID",
            type: "text",
            helpText: "Discord thread ID for application",
          },
          {
            key: "reminderLastSentAt",
            label: "Reminder Last Sent At",
            type: "date",
            helpText: "When reminder was last sent",
          },
          {
            key: "publicSlug",
            label: "Public Slug",
            type: "text",
            helpText: "URL-friendly slug for public profile",
          },
        ],
      },
    ],
  },
  Village: {
    name: "Village",
    displayName: "Villages",
    icon: "fa-building",
    collection: "villages",
    nameField: "name",
    sortField: "name",
    filterKeys: ["region"],
    tabs: [
      {
        id: "basics",
        label: "Basics",
        icon: "fa-tag",
        gridColumns: 2,
        fields: [
          {
            key: "name",
            label: "Name",
            type: "text",
            helpText: "Village name",
            required: true,
          },
          {
            key: "region",
            label: "Region",
            type: "text",
            helpText: "Village region",
            required: true,
          },
          {
            key: "color",
            label: "Color",
            type: "text",
            helpText: "Village color (hex code)",
            required: true,
          },
          {
            key: "emoji",
            label: "Emoji",
            type: "text",
            helpText: "Village emoji",
            required: true,
          },
          {
            key: "level",
            label: "Level",
            type: "number",
            helpText: "Village level",
            min: 1,
            max: 3,
          },
          {
            key: "status",
            label: "Status",
            type: "select",
            helpText: "Village status",
            options: [
              { value: "upgradable", label: "Upgradable" },
              { value: "damaged", label: "Damaged" },
              { value: "max", label: "Max" },
            ],
          },
        ],
      },
      {
        id: "health",
        label: "Health",
        icon: "fa-heart",
        gridColumns: 2,
        fields: [
          {
            key: "health",
            label: "Current Health",
            type: "number",
            helpText: "Current village health",
            min: 0,
          },
          {
            key: "levelHealth",
            label: "Level Health",
            type: "text",
            helpText: "Health by level (Map: level -> health). Format: JSON object like {\"1\": 100, \"2\": 200, \"3\": 300}",
          },
          {
            key: "lastDamageTime",
            label: "Last Damage Time",
            type: "date",
            helpText: "When the village was last damaged",
          },
        ],
      },
      {
        id: "tokens",
        label: "Tokens",
        icon: "fa-coins",
        gridColumns: 2,
        fields: [
          {
            key: "currentTokens",
            label: "Current Tokens",
            type: "number",
            helpText: "Current token count",
            min: 0,
          },
          {
            key: "tokenRequirements",
            label: "Token Requirements",
            type: "text",
            helpText: "Token requirements by level (Map: level -> tokens). Format: JSON object like {\"2\": 10000, \"3\": 50000}",
          },
        ],
      },
      {
        id: "materials",
        label: "Materials",
        icon: "fa-box",
        gridColumns: 1,
        fields: [
          {
            key: "materials",
            label: "Materials",
            type: "custom",
            component: "VillageMaterialsField",
            helpText: "Materials required for upgrades. Add materials and set current amounts and requirements for levels 2 and 3",
          },
        ],
      },
      {
        id: "contributors",
        label: "Contributors",
        icon: "fa-users",
        gridColumns: 1,
        fields: [
          {
            key: "contributors",
            label: "Contributors",
            type: "custom",
            component: "VillageContributorsField",
            helpText: "Contributors data. Add contributors by ID, then add items and set token amounts",
          },
        ],
      },
      {
        id: "cooldowns",
        label: "Cooldowns",
        icon: "fa-clock",
        gridColumns: 1,
        fields: [
          {
            key: "cooldowns",
            label: "Cooldowns",
            type: "custom",
            component: "VillageCooldownsField",
            helpText: "Cooldowns data. Add cooldown keys and set their date/time values",
          },
        ],
      },
      {
        id: "raids",
        label: "Raid Quota",
        icon: "fa-shield-alt",
        gridColumns: 2,
        fields: [
          {
            key: "raidQuotaPeriodStart",
            label: "Raid Quota Period Start",
            type: "date",
            helpText: "Start date of the raid quota period",
          },
          {
            key: "raidQuotaCount",
            label: "Raid Quota Count",
            type: "number",
            helpText: "Number of raids in current quota period",
            min: 0,
          },
          {
            key: "raidQuotaPeriodType",
            label: "Raid Quota Period Type",
            type: "select",
            helpText: "Type of raid quota period",
            options: [
              { value: "week", label: "Week" },
              { value: "biweek", label: "Biweek" },
              { value: "month", label: "Month" },
            ],
          },
          {
            key: "lastQuotaRaidTime",
            label: "Last Quota Raid Time",
            type: "date",
            helpText: "Time of last raid in quota period",
          },
        ],
      },
      {
        id: "vending",
        label: "Vending",
        icon: "fa-store",
        gridColumns: 2,
        fields: [
          {
            key: "vendingTier",
            label: "Vending Tier",
            type: "number",
            helpText: "Vending tier level",
            min: 1,
          },
          {
            key: "vendingDiscount",
            label: "Vending Discount",
            type: "number",
            helpText: "Vending discount percentage",
            min: 0,
            max: 100,
          },
        ],
      },
    ],
  },
  Inventory: {
    name: "Inventory",
    displayName: "Character Inventories",
    icon: "fa-box-open",
    collection: "inventories",
    nameField: "itemName",
    sortField: "itemName",
    filterKeys: ["category", "type", "characterId"],
    tabs: [
      {
        id: "basics",
        label: "Basics",
        icon: "fa-tag",
        gridColumns: 2,
        fields: [
          {
            key: "characterId",
            label: "Character ID",
            type: "text",
            helpText: "ObjectId of the character who owns this inventory entry",
            required: true,
          },
          {
            key: "itemName",
            label: "Item Name",
            type: "text",
            helpText: "Display name of the item",
            required: true,
          },
          {
            key: "itemId",
            label: "Item ID",
            type: "text",
            helpText: "ObjectId reference to the Item model",
            required: true,
          },
          {
            key: "quantity",
            label: "Quantity",
            type: "number",
            helpText: "Number of this item (default 1)",
            min: 1,
          },
          {
            key: "category",
            label: "Category",
            type: "select",
            helpText: "Item category",
            options: [
              { value: "", label: "(none)" },
              ...FIELD_OPTIONS.category.map((c) => ({ value: c, label: c })),
            ],
          },
          {
            key: "type",
            label: "Type",
            type: "select",
            helpText: "Item type",
            options: [
              { value: "", label: "(none)" },
              ...FIELD_OPTIONS.type.map((t) => ({ value: t, label: t })),
            ],
          },
          {
            key: "subtype",
            label: "Subtype",
            type: "select",
            helpText: "Item subtype",
            options: [
              { value: "", label: "(none)" },
              ...FIELD_OPTIONS.subtype.map((s) => ({ value: s, label: s })),
            ],
          },
          {
            key: "job",
            label: "Job",
            type: "select",
            helpText: "Associated job",
            options: [
              { value: "", label: "(none)" },
              { value: "Adventurer", label: "Adventurer" },
              { value: "Artist", label: "Artist" },
              { value: "Beekeeper", label: "Beekeeper" },
              { value: "Blacksmith", label: "Blacksmith" },
              { value: "Cook", label: "Cook" },
              { value: "Craftsman", label: "Craftsman" },
              { value: "Farmer", label: "Farmer" },
              { value: "Fisherman", label: "Fisherman" },
              { value: "Forager", label: "Forager" },
              { value: "Gravekeeper", label: "Gravekeeper" },
              { value: "Guard", label: "Guard" },
              { value: "Herbalist", label: "Herbalist" },
              { value: "Hunter", label: "Hunter" },
              { value: "Hunter (Looting)", label: "Hunter (Looting)" },
              { value: "Mask Maker", label: "Mask Maker" },
              { value: "Mercenary", label: "Mercenary" },
              { value: "Miner", label: "Miner" },
              { value: "Rancher", label: "Rancher" },
              { value: "Researcher", label: "Researcher" },
              { value: "Scout", label: "Scout" },
              { value: "Weaver", label: "Weaver" },
              { value: "Witch", label: "Witch" },
            ],
          },
          {
            key: "perk",
            label: "Perk",
            type: "text",
            helpText: "Associated perk",
          },
          {
            key: "location",
            label: "Location",
            type: "text",
            helpText: "Item location",
          },
          {
            key: "obtain",
            label: "Obtain",
            type: "select",
            helpText: "How the item was obtained",
            options: [
              { value: "", label: "(none)" },
              { value: "Looted", label: "Looted" },
              { value: "Crafted", label: "Crafted" },
              { value: "Crafting", label: "Crafting" },
              { value: "Gathered", label: "Gathered" },
              { value: "Traveling", label: "Traveling" },
              { value: "Exploring", label: "Exploring" },
              { value: "Vending", label: "Vending" },
              { value: "Trade", label: "Trade" },
              { value: "Manual Sync", label: "Manual Sync" },
              { value: "Manual", label: "Manual" },
              { value: "Manual Entry", label: "Manual Entry" },
              { value: "Quest Reward", label: "Quest Reward" },
              { value: "Unknown", label: "Unknown" },
            ],
          },
          {
            key: "synced",
            label: "Synced",
            type: "text",
            helpText: "Unique identifier for synced items (leave empty if not synced)",
          },
          {
            key: "fortuneTellerBoost",
            label: "Fortune Teller Boost",
            type: "boolean",
            helpText: "Tag for items crafted with Fortune Teller boost (sell for 20% more)",
          },
        ],
      },
      {
        id: "dates",
        label: "Dates",
        icon: "fa-calendar",
        gridColumns: 2,
        fields: [
          {
            key: "date",
            label: "Date",
            type: "date",
            helpText: "Date associated with the item",
          },
          {
            key: "craftedAt",
            label: "Crafted At",
            type: "date",
            helpText: "When the item was crafted (if applicable)",
          },
          {
            key: "gatheredAt",
            label: "Gathered At",
            type: "date",
            helpText: "When the item was gathered (if applicable)",
          },
        ],
      },
    ],
  },
};

// Helper function to get model config
export function getModelConfig(modelName: string): ModelConfig | undefined {
  return MODEL_CONFIGS[modelName];
}

// Helper function to get all available model names
export function getAvailableModelNames(): string[] {
  return Object.keys(MODEL_CONFIGS);
}
