
// ------------------- Define general item categories -------------------
// Organized categories with corresponding items under each category
const generalCategories = {
  'Any Ancient Material': [
    'Ancient Core',
    'Ancient Gear',
    'Ancient Screw',
    'Ancient Shaft',
    'Ancient Spring',
    'Giant Ancient Core'
  ],
  'Any Bass': [
    'Hearty Bass',
    'Hyrule Bass',
    'Staminoka Bass'
  ],
  'Any Carp': [
    'Armored Carp',
    'Mighty Carp',
    'Sanke Carp'
  ],
  'Any Carrot': [
    'Endura Carrot',
    'Swift Carrot'
  ],
  'Any Crab': [
    'Bright-Eyed Crab',
    'Ironshell Crab',
    'Razorclaw Crab'
  ],
  'Any Fish': [
    'Ancient Arowana',
    'Armored Carp',
    'Armored Porgy',
    'Chillfin Trout',
    'Glowing Cave Fish',
    'Hearty Bass',
    'Hearty Salmon',
    'Hyrule Bass',
    'Mighty Carp',
    'Mighty Porgy',
    'Sanke Carp',
    'Sizzlefin Trout',
    'Staminoka Bass',
    'Stealthfin Trout',
    'Voltfin Trout'
  ],
  'Any Fruit': [
    'Apple',
    'Dazzlefruit',
    'Fire Fruit',
    'Fleet-Lotus Seeds',
    'Golden Apple',
    'Hearty Durian',
    'Hydromelon',
    'Ice Fruit',
    'Mighty Bananas',
    'Palm Fruit',
    'Shock Fruit',
    'Spicy Pepper',
    'Splash Fruit',
    'Thornberry',
    'Voltfruit',
    'Wild berry'
  ],
  'Any Lizard': [
    'Fireproof Lizard',
    'Hearty Lizard',
    'Hightail Lizard'
  ],
  'Any Monster Part': [
    'Blin Bling',
    'Bokoblin Fang',
    'Bokoblin Guts',
    'Bokoblin Horn',
    'Chuchu Egg',
    'Chuchu Jelly',
    'Electric Keese Wing',
    'Fire Keese Wing',
    'Freezard Water',
    'Gibdo Bandage',
    'Gibdo Bone',
    'Gibdo Guts',
    'Gibdo Wing',
    'Golden Skull',
    'Hinox Guts',
    'Hinox Toenail',
    'Hinox Tooth',
    'Horriblin Claw',
    'Horriblin Guts',
    'Horriblin Horn',
    'Ice Keese Wing',
    'Icy Lizalfos Tail',
    'Keese Eyeball',
    'Keese Wing',
    'Like Like Stone',
    'Lizalfos Horn',
    'Lizalfos Tail',
    'Lizalfos Talon',
    'Lynel Guts',
    'Lynel Hoof',
    'Lynel Horn',
    'Moblin Fang',
    'Moblin Guts',
    'Moblin Horn',
    'Molduga Fin',
    'Molduga Guts',
    'Monster Claw',
    'Monster Extract',
    'Monster Horn',
    'Octo Balloon',
    'Octorok Eyeball',
    'Octorok Tentacle',
    'Ornamental Skull',
    'Poe Soul',
    'Red Chuchu Jelly',
    'Red Lizalfos Tail',
    'Rugged Horn',
    'Serpent Fangs',
    'Spider\'s Eye',
    'Stal Skull',
    'White Chuchu Jelly',
    'Yellow Chuchu Jelly',
    'Yellow Lizalfos Tail'
  ],
  'Any Mushroom': [
    'Brightcap',
    'Chillshroom',
    'Endura Shroom',
    'Hearty Truffle',
    'Hylian Shroom',
    'Ironshroom',
    'Puffshroom',
    'Razorshroom',
    'Rushroom',
    'Silent Shroom',
    'Skyshroom',
    'Stamella Shroom',
    'Sunshroom',
    'Sweet Shroom',
    'Zapshroom'
  ],
  'Any Nut': [
    'Chickaloo Tree Nut',
    'Acorn'
  ],
  'Any Ore': [
    'Amber',
    'Amber Relic',
    'Amethyst',
    'Aurora Stone',
    'Blight Geodes',
    'Carmine Pearl',
    'Chill Stone',
    'Crystal Skull',
    'Demon Fossil',
    'Diamond',
    'Dusk Relic',
    'Eldin Ore',
    'Emerald',
    'Fairy Dust',
    'Flint',
    'Goddess Plume',
    'Gold Dust',
    'Gold Ore',
    'Goron Ore',
    'Jade Relic',
    'Lava Drop',
    'Luminous Stone',
    'Opal',
    'Rainbow Coral',
    'Rock Salt',
    'Ruby',
    'Sapphire',
    'Silver Dust',
    'Silver Ore',
    'Topaz',
    'Iron Bar',
    'Gold Bar',
    'Silver Bar'
  ],
  'Any Plant': [
    'Acorn',
    'Ancient Flower',
    'Armoranth',
    'Blue Nightshade',
    'Brightbloom Seed',
    'Cane Sugar',
    'Carrumpkin',
    'Chickaloo Tree Nut',
    'Cool Safflina',
    'Electric Safflina',
    'Endura Carrot',
    'Fortified Pumpkin',
    'Hearty Radish',
    'Hylian Rice',
    'Hylian Tomato',
    'Hyrule Herb',
    'Ice Rose',
    'Kelp',
    'Mighty Thistle',
    'Muddle Bud',
    'Silent Princess',
    'Stambulb',
    'Sundelion',
    'Swift Carrot',
    'Swift Violet',
    'Tabantha Wheat',
    'Warm Safflina'
  ],
  'Any Porgy': [
    'Armored Porgy',
    'Mighty Porgy'
  ],
  'Any Raw Meat': [
    'Raw Bird Drumstick',
    'Raw Bird Thigh',
    'Raw Gourmet Meat',
    'Raw Meat',
    'Raw Prime Meat',
    'Raw Whole Bird'
  ],
  'Any Seafood': [
    'Ancient Arowana',
    'Armored Carp',
    'Armored Porgy',
    'Bright-Eyed Crab',
    'Chillfin Trout',
    'Glowing Cave Fish',
    'Hearty Bass',
    'Hearty Blueshell Snail',
    'Hearty Salmon',
    'Hyrule Bass',
    'Ironshell Crab',
    'Mighty Carp',
    'Mighty Porgy',
    'Razorclaw Crab',
    'Sanke Carp',
    'Sizzlefin Trout',
    'Sneaky River Snail',
    'Staminoka Bass',
    'Stealthfin Trout',
    'Voltfin Trout'
  ],
  'Any Snail': [
    'Hearty Blueshell Snail',
    'Sneaky River Snail'
  ],
  'Any Trout': [
    'Chillfin Trout',
    'Sizzlefin Trout',
    'Stealthfin Trout',
    'Voltfin Trout'
  ],
  'Any Organic Material': [
    'Acorn',
    'Ancient Arowana',
    'Ancient Flower',
    'Armoranth',
    'Armored Carp',
    'Armored Porgy',
    'Apple',
    'Blue Nightshade',
    'Bright-Eyed Crab',
    'Brightbloom Seed',
    'Brightcap',
    'Cane Sugar',
    'Carrumpkin',
    'Chickaloo Tree Nut',
    'Chillfin Trout',
    'Chillshroom',
    'Cool Safflina',
    'Dazzlefruit',
    'Electric Safflina',
    'Endura Carrot',
    'Endura Shroom',
    'Fire Fruit',
    'Fireproof Lizard',
    'Fleet-Lotus Seeds',
    'Fortified Pumpkin',
    'Glowing Cave Fish',
    'Golden Apple',
    'Hearty Bass',
    'Hearty Blueshell Snail',
    'Hearty Durian',
    'Hearty Lizard',
    'Hearty Radish',
    'Hearty Salmon',
    'Hearty Shroom',
    'Hearty Truffle',
    'Hightail Lizard',
    'Hydromelon',
    'Hylian Rice',
    'Hylian Shroom',
    'Hylian Tomato',
    'Hyrule Bass',
    'Hyrule Herb',
    'Ice Fruit',
    'Ice Rose',
    'Ironshell Crab',
    'Ironshroom',
    'Kelp',
    'Mighty Bananas',
    'Mighty Carp',
    'Mighty Porgy',
    'Mighty Thistle',
    'Muddle Bud',
    'Palm Fruit',
    'Puffshroom',
    'Razorclaw Crab',
    'Razorshroom',
    'Raw Bird Drumstick',
    'Raw Bird Thigh',
    'Raw Gourmet Meat',
    'Raw Meat',
    'Raw Prime Meat',
    'Raw Whole Bird',
    'Rushroom',
    'Sanke Carp',
    'Silent Princess',
    'Silent Shroom',
    'Skyshroom',
    'Sneaky River Snail',
    'Splash Fruit',
    'Spicy Pepper',
    'Tabantha Wheat',
    'Staminoka Bass',
    'Stamella Shroom',
    'Stambulb',
    'Stealthfin Trout',
    'Sunshroom',
    'Sundelion',
    'Swift Carrot',
    'Swift Violet',
    'Sweet Shroom',
    'Thornberry',
    'Voltfin Trout',
    'Voltfruit',
    'Warm Safflina',
    'Wild berry',
    'Zapshroom'
  ]
};

// ------------------- Export the general categories -------------------
module.exports = generalCategories;

