// ------------------- Import necessary modules -------------------
const mongoose = require('mongoose');
const { Schema } = mongoose;

// ------------------- Schema for monsters -------------------
const MonsterSchema = new Schema({
  name: { type: String, required: true }, // Readable name
  nameMapping: { type: String, required: true }, // Key format for mapping
  image: { type: String, default: 'No Image' },
  species: { type: String, default: 'Unknown' },
  type: { type: String, default: 'Unknown' },
  element: { 
    type: String, 
    enum: ['none', 'fire', 'ice', 'electric', 'water', 'earth', 'undead', 'wind'],
    default: 'none' 
  }, // Elemental type for elixir resistance matching
  tier: { type: Number, default: 1 },
  hearts: { type: Number, default: 0 },
  dmg: { type: Number, default: 0 },
  bloodmoon: { type: Boolean, default: false },
  // Location flags
  locations: { type: [String], default: [] },
  eldin: { type: Boolean, default: false },
  lanayru: { type: Boolean, default: false },
  faron: { type: Boolean, default: false },
  centralHyrule: { type: Boolean, default: false },
  gerudo: { type: Boolean, default: false },
  hebra: { type: Boolean, default: false },
  pathOfScarletLeaves: { type: Boolean, default: false },
  leafDewWay: { type: Boolean, default: false },
  exploreLocations: { type: [String], default: [] },
  exploreEldin: { type: Boolean, default: false },
  exploreLanayru: { type: Boolean, default: false },
  exploreFaron: { type: Boolean, default: false },
  // Jobs associated with the monster
  job: { type: [String], default: [] },
  adventurer: { type: Boolean, default: false },
  guard: { type: Boolean, default: false },
  graveskeeper: { type: Boolean, default: false },
  hunter: { type: Boolean, default: false },
  mercenary: { type: Boolean, default: false },
  scout: { type: Boolean, default: false },
  rancher: { type: Boolean, default: false },
  beekeeper: { type: Boolean, default: false },
  farmer: { type: Boolean, default: false },
  fisherman: { type: Boolean, default: false },
  forager: { type: Boolean, default: false },
  herbalist: { type: Boolean, default: false },
  miner: { type: Boolean, default: false }
}, { collection: 'monsters' });

// ------------------- Index on name for quick lookup -------------------
MonsterSchema.index({ name: 1 });

// ------------------- Monster name mapping -------------------
const monsterMapping = {
  blackBokoblin: { name: 'Black Bokoblin', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Bokoblin_Black.png' },
  blueBokoblin: { name: 'Blue Bokoblin', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Bokoblin_Blue.png' },
  cursedBokoblin: { name: 'Cursed Bokoblin', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Cursed_Bokoblin.png' },
  goldenBokoblin: { name: 'Golden Bokoblin', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Bokoblin_Gold.png' },
  silverBokoblin: { name: 'Silver Bokoblin', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Bokoblin_Silver.png' },
  bokoblin: { name: 'Bokoblin', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Bokoblin.png' },
  electricChuchuLarge: { name: 'Electric Chuchu (Large)', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Chuchu_Electric_Large.png' },
  fireChuchuLarge: { name: 'Fire Chuchu (Large)', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Chuchu_Fire_Large.png' },
  iceChuchuLarge: { name: 'Ice Chuchu (Large)', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Chuchu_Ice_Large.png' },
  chuchuLarge: { name: 'Chuchu (Large)', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Chuchu_Large.png' },
  electricChuchuMedium: { name: 'Electric Chuchu (Medium)', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Chuchu_Electric_Medium.png' },
  fireChuchuMedium: { name: 'Fire Chuchu (Medium)', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Chuchu_Fire_Medium.png' },
  iceChuchuMedium: { name: 'Ice Chuchu (Medium)', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Chuchu_Ice_Medium.png' },
  chuchuMedium: { name: 'Chuchu (Medium)', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Chuchu_Medium.png' },
  electricChuchuSmall: { name: 'Electric Chuchu (Small)', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Chuchu_Electric_Small.png' },
  fireChuchuSmall: { name: 'Fire Chuchu (Small)', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Chuchu_Fire_Small.png' },
  iceChuchuSmall: { name: 'Ice Chuchu (Small)', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Chuchu_Ice_Small.png' },
  chuchuSmall: { name: 'Chuchu (Small)', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Chuchu_Small.png' },
  blackHinox: { name: 'Black Hinox', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Hinox_Black.png' },
  blueHinox: { name: 'Blue Hinox', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Hinox_Blue.png' },
  hinox: { name: 'Hinox', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Hinox.png' },
  electricKeese: { name: 'Electric Keese', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Keese_Electric.png' },
  fireKeese: { name: 'Fire Keese', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Keese_Fire.png' },
  iceKeese: { name: 'Ice Keese', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Keese_Ice.png' },
  keese: { name: 'Keese', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Keese.png' },
  blackLizalfos: { name: 'Black Lizalfos', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Lizalfos_Black.png' },
  blueLizalfos: { name: 'Blue Lizalfos', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Lizalfos_Blue.png' },
  cursedLizalfos: { name: 'Cursed Lizalfos', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Cursed_Lizalfos.png' },
  electricLizalfos: { name: 'Electric Lizalfos', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Lizalfos_Electric.png' },
  fireBreathLizalfos: { name: 'Fire-breath Lizalfos', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Lizalfos_Firebreathing.png' },
  goldenLizalfos: { name: 'Golden Lizalfos', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Lizalfos_Gold.png' },
  iceBreathLizalfos: { name: 'Ice-breath Lizalfos', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Lizalfos_Icebreathing.png' },
  silverLizalfos: { name: 'Silver Lizalfos', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Lizalfos_Silver.png' },
  lizalfos: { name: 'Lizalfos', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Lizalfos.png' },
  blueManedLynel: { name: 'Blue-Maned Lynel', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Lynel_Blue.png' },
  goldenLynel: { name: 'Golden Lynel', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Lynel_Gold.png' },
  silverLynel: { name: 'Silver Lynel', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Lynel_Silver.png' },
  whiteManedLynel: { name: 'White-maned Lynel', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Lynel_White.png' },
  lynel: { name: 'Lynel', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Lynel.png' },
  blackMoblin: { name: 'Black Moblin', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Moblin_Black.png' },
  blueMoblin: { name: 'Blue Moblin', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Moblin_Blue.png' },
  cursedMoblin: { name: 'Cursed Moblin', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Cursed_Moblin.png' },
  goldenMoblin: { name: 'Golden Moblin', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Moblin_Gold.png' },
  silverMoblin: { name: 'Silver Moblin', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Moblin_Silver.png' },
  moblin: { name: 'Moblin', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Moblin.png' },
  molduga: { name: 'Molduga', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Molduga.png' },
  molduking: { name: 'Molduking', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Molduking.png' },
  forestOctorok: { name: 'Forest Octorok', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Octorok_Forest.png' },
  rockOctorok: { name: 'Rock Octorok', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Octorok_Rock.png' },
  skyOctorok: { name: 'Sky Octorok', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Octorok_Sky.png' },
  snowOctorok: { name: 'Snow Octorok', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Octorok_Snow.png' },
  treasureOctorok: { name: 'Treasure Octorok', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Octorok_Treasure.png' },
  waterOctorok: { name: 'Water Octorok', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Octorok_Water.png' },
  frostPebblit: { name: 'Frost Pebblit', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Pebblit_Frost.png' },
  igneoPebblit: { name: 'Igneo Pebblit', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Pebblit_Igneo.png' },
  stonePebblit: { name: 'Stone Pebblit', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Pebblit_Stone.png' },
  stalizalfos: { name: 'Stalizalfos', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Stalizalfos.png' },
  stalkoblin: { name: 'Stalkoblin', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Stalkoblin.png' },
  stalmoblin: { name: 'Stalmoblin', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Stalmoblin.png' },
  stalnox: { name: 'Stalnox', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Stalhinox.png' },
  frostTalus: { name: 'Frost Talus', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Talus_Frost.png' },
  igneoTalus: { name: 'Igneo Talus', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Talus_Igneo.png' },
  luminousTalus: { name: 'Luminous Talus', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Talos_Luminous.png' },
  rareTalus: { name: 'Rare Talus', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Talus_Rare.png' },
  stoneTalus: { name: 'Stone Talus', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Talus_Stone.png' },
  blizzardWizzrobe: { name: 'Blizzard Wizzrobe', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Wizzrobe_Blizard.png' },
  electricWizzrobe: { name: 'Electric Wizzrobe', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Wizzrobe_Electric.png' },
  fireWizzrobe: { name: 'Fire Wizzrobe', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Wizzrobe_Fire.png' },
  iceWizzrobe: { name: 'Ice Wizzrobe', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Wizzrobe_Ice.png' },
  meteoWizzrobe: { name: 'Meteo Wizzrobe', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Wizzrobe_Meteo.png' },
  thunderWizzrobe: { name: 'Thunder Wizzrobe', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Wizzrobe_Thunder.png' },
  likeLike: { name: 'Like Like', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Like-Like.png' },
  evermean: { name: 'Evermean', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Evermean.png' },
  gibdo: { name: 'Gibdo', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Gibdo.png' },
  horriblin: { name: 'Horriblin', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Horriblin.png' },
  gloomHands: { name: 'Gloom Hands', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_GloomHands.png' },
  bossBokoblin: { name: 'Boss Bokoblin', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Bokoblin_Boss.png' },
  mothGibdo: { name: 'Moth Gibdo', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Gibdo_Moth.png' },
  littleFrox: { name: 'Little Frox', image: 'https://storage.googleapis.com/tinglebot/Monsters/%5BRotW%5D%20Monsters_Frox.png' },
  yigaBlademaster: { name: 'Yiga Blademaster', image: 'https://storage.googleapis.com/tinglebot/Monsters/Monsters_Yiga_Blademaster.png' },
  yigaFootsoldier: { name: 'Yiga Footsoldier', image: 'https://storage.googleapis.com/tinglebot/Monsters/Monsters_Yiga_Footsoldier.png' },
};

module.exports = mongoose.model('Monster', MonsterSchema);
module.exports.monsterMapping = monsterMapping;
